server:
  port: 9005

  #eureka:
  #  client:
  #    serviceUrl:
  #      defaultZone: http://eureka8080.com:8080/eureka/
  #                      spring:
  #                        profiles:
  #                          active: native




spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LightMoney/firstCloud.git
          search-paths: conf
          username: LightMoney
          password: fan85719223
#          label:分支默认master